#!/bin/bash

# shellcheck shell=bash

export DOCUMENT_ENGINE_IMAGE_REPOSITORY="${DOCUMENT_ENGINE_IMAGE_REPOSITORY:-public.ecr.aws/pspdfkit/document-engine}"
export DOCUMENT_ENGINE_IMAGE_TAG="${DOCUMENT_ENGINE_IMAGE_TAG:-latest}"
export DOCUMENT_ENGINE_IMAGE="${DOCUMENT_ENGINE_IMAGE:-${DOCUMENT_ENGINE_IMAGE_REPOSITORY}:${DOCUMENT_ENGINE_IMAGE_TAG}}"
export CADDY_IMAGE="${CADDY_IMAGE:-caddy:2.10}"
export POSTGRES_IMAGE="${POSTGRES_IMAGE:-postgres:16}"
export MINIO_IMAGE="${MINIO_IMAGE:-minio/minio}"
export MINIO_MC_IMAGE="${MINIO_MC_IMAGE:-minio/mc}"

export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-de-docker-compose}"
export CADDY_HTTP_PORT="${CADDY_HTTP_PORT:-5000}"
export MINIO_CONSOLE_PORT="${MINIO_CONSOLE_PORT:-9001}"

export POSTGRES_USER="${POSTGRES_USER:-de-user}"
export POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-password}"
export POSTGRES_DB="${POSTGRES_DB:-document-engine}"
export SECRET_KEY_BASE="${SECRET_KEY_BASE:-secret-key-base}"
export API_AUTH_TOKEN="${API_AUTH_TOKEN:-secret}"
export DASHBOARD_USERNAME="${DASHBOARD_USERNAME:-admin}"
export DASHBOARD_PASSWORD="${DASHBOARD_PASSWORD:-admin}"
export ACTIVATION_KEY="${ACTIVATION_KEY:-}"

export MINIO_ROOT_USER="${MINIO_ROOT_USER:-pspdfkitObjectStorageRootKey}"
export MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-pspdfkitObjectStorageRootPassword}"
export ASSET_STORAGE_S3_ACCESS_KEY_ID="${ASSET_STORAGE_S3_ACCESS_KEY_ID:-$MINIO_ROOT_USER}"
export ASSET_STORAGE_S3_SECRET_ACCESS_KEY="${ASSET_STORAGE_S3_SECRET_ACCESS_KEY:-$MINIO_ROOT_PASSWORD}"
export ASSET_STORAGE_S3_HOST="${ASSET_STORAGE_S3_HOST:-minio}"
export ASSET_STORAGE_S3_PORT="${ASSET_STORAGE_S3_PORT:-9000}"
export ASSET_STORAGE_S3_SCHEME="${ASSET_STORAGE_S3_SCHEME:-http://}"
export ASSET_STORAGE_S3_REGION="${ASSET_STORAGE_S3_REGION:-us-east-1}"

# Local profile for exercising multi-GB uploads from the dashboard.
#
# These defaults are intended for local manual testing while still allowing
# callers to override any setting.
export ASSET_STORAGE_BACKEND="${ASSET_STORAGE_BACKEND:-s3}"
export ASSET_STORAGE_S3_BUCKET="${ASSET_STORAGE_S3_BUCKET:-pspdfkit-dev}"
export HTTP2_SHARED_RENDERING_PROCESS_ENABLE="${HTTP2_SHARED_RENDERING_PROCESS_ENABLE:-true}"
export HTTP2_SHARED_RENDERING_PROCESS_CHECKIN_TIMEOUT="${HTTP2_SHARED_RENDERING_PROCESS_CHECKIN_TIMEOUT:-1000}"
export HTTP2_SHARED_RENDERING_PROCESS_CHECKOUT_TIMEOUT="${HTTP2_SHARED_RENDERING_PROCESS_CHECKOUT_TIMEOUT:-900000}"
export MAX_UPLOAD_SIZE_BYTES="${MAX_UPLOAD_SIZE_BYTES:-50000000000}"
export SERVER_REQUEST_TIMEOUT="${SERVER_REQUEST_TIMEOUT:-900000}"
export PSPDFKIT_WORKER_TIMEOUT="${PSPDFKIT_WORKER_TIMEOUT:-900000}"
export FILE_UPLOAD_TIMEOUT_MS="${FILE_UPLOAD_TIMEOUT_MS:-900000}"
export READ_ANNOTATION_BATCH_TIMEOUT="${READ_ANNOTATION_BATCH_TIMEOUT:-300000}"
export ASSET_STORAGE_CACHE_SIZE="${ASSET_STORAGE_CACHE_SIZE:-20000000000}"
export ASSET_STORAGE_CACHE_TIMEOUT="${ASSET_STORAGE_CACHE_TIMEOUT:-30000}"
