packages:
  - .
minimumReleaseAge: 21600 # 15 days
overrides:
  "@babel/core@<=7.29.0": ">=7.29.6 <8"
  "ajv@<6.14.0": ">=6.14.0 <7"
  "brace-expansion@<1.1.18": ">=1.1.18 <2"
  "brace-expansion@>=2.0.0 <2.1.4": ">=2.1.4 <3"
  "brace-expansion@>=4.0.0 <5.0.9": ">=5.0.9 <6"
  "browserslist@<=4.28.6": ">=4.28.8 <5"
  "dompurify@<3.4.13": ">=3.4.13 <4"
  "flatted@<3.4.2": ">=3.4.2 <4"
  "js-yaml@>=4.0.0 <4.3.1": ">=4.3.1 <5"
  "linkify-it@<=5.0.1": ">=5.0.2 <6"
  "lodash@<4.18.0": ">=4.18.0 <5"
  "markdown-it@<14.2.0": ">=14.2.0 <15"
  "minimatch@<3.1.4": ">=3.1.4 <4"
  "minimatch@>=9.0.0 <9.0.7": ">=9.0.7 <10"
  "nanoid@<3.3.18": ">=3.3.18 <4"
  "nanoid@>=4.0.0 <5.1.16": ">=5.1.16 <6"
  "picomatch@<2.3.2": ">=2.3.2 <3"
  "picomatch@>=4.0.0 <4.0.5": ">=4.0.5 <5"
  "postcss@<8.5.23": ">=8.5.23 <9"
  "sharp@<0.35.0": ">=0.35.0 <1"
